######################################################################
# Automatically generated by qmake (3.0) ?? 7? 15 18:08:33 2017
######################################################################

TEMPLATE = app
TARGET = example_09-05
INCLUDEPATH += .

# Input
SOURCES += example_09-05.cpp
