######################################################################
# Automatically generated by qmake (3.0) ?? 7? 15 18:44:13 2017
######################################################################
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = e9-5qt
INCLUDEPATH += .

# Input
HEADERS += QMoviePlayer.h
FORMS += QMoviePlayer.ui
SOURCES += example_09-05.cpp QMoviePlayer.cpp
